#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = ROOT / "docs"
OUT_HTML = DOCS_DIR / "docs_urls.html"
OUT_JSON = DOCS_DIR / "docs_urls.json"


def is_hidden(p: Path) -> bool:
    return any(part.startswith(".") for part in p.parts)


def rel_to_docs(p: Path) -> str:
    return p.relative_to(DOCS_DIR).as_posix()


def collect_docs_paths() -> list[str]:
    if not DOCS_DIR.exists():
        return []

    paths: list[str] = []
    for p in DOCS_DIR.rglob("*"):
        if p.is_dir():
            continue
        if is_hidden(p):
            continue
        # Keep it meaningful: html + md + json + txt
        if p.suffix.lower() not in {".html", ".md", ".json", ".txt"}:
            continue
        paths.append(rel_to_docs(p))
    return sorted(paths)


def compute_repo_base() -> str:
    """
    Returns '/<repo>/' for GitHub Pages project sites like:
      https://user.github.io/REPO/...
    If not detectable, returns '/'.
    """
    # We embed JS that computes this at runtime; this is just a placeholder for template clarity.
    return "/"


# Inline map-loader: no external asset required.
# It creates a floating button linking to map.html (and a secondary handshake link).
MAP_LOADER_INLINE = r"""
<script>
(function(){
  try {
    if (window.__acaciaMapLoaderInstalled) return;
    window.__acaciaMapLoaderInstalled = true;

    // Detect GitHub Pages project base: '/REPO/...'
    // If pathname looks like '/REPO/docs/docs_urls.html', base becomes '/REPO/'
    var path = (location && location.pathname) ? location.pathname : "/";
    var parts = path.split("/").filter(Boolean);
    var base = "/";
    if (parts.length >= 1) base = "/" + parts[0] + "/";

    function mkBtn(text, href, rightPx){
      var a = document.createElement("a");
      a.textContent = text;
      a.href = base + href.replace(/^\/+/, "");
      a.style.position = "fixed";
      a.style.bottom = "18px";
      a.style.right = rightPx + "px";
      a.style.zIndex = "99999";
      a.style.padding = "10px 12px";
      a.style.borderRadius = "999px";
      a.style.background = "rgba(15, 23, 42, 0.75)";
      a.style.border = "1px solid rgba(148, 163, 184, 0.35)";
      a.style.color = "#e5e7eb";
      a.style.font = "600 12px system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif";
      a.style.letterSpacing = ".08em";
      a.style.textTransform = "uppercase";
      a.style.textDecoration = "none";
      a.style.backdropFilter = "blur(6px)";
      a.style.boxShadow = "0 10px 30px rgba(0,0,0,.25)";
      a.onmouseenter = function(){ a.style.background = "rgba(30, 41, 59, 0.85)"; };
      a.onmouseleave = function(){ a.style.background = "rgba(15, 23, 42, 0.75)"; };
      return a;
    }

    // Map button
    document.body.appendChild(mkBtn("Map", "map.html", 18));
    // Handshake button (optional, but awesome)
    document.body.appendChild(mkBtn("Handshake", "handshake.html", 86));

  } catch (e) {}
})();
</script>
""".strip()


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Acacia • docs_urls</title>
  <style>
    :root {{
      --bg:#050812; --panel:rgba(15,23,42,.72); --border:rgba(148,163,184,.22);
      --text:#e5e7eb; --muted:#94a3b8; --link:#7dd3fc;
    }}
    body {{ margin:0; font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; background:var(--bg); color:var(--text); }}
    .wrap {{ max-width: 980px; margin: 0 auto; padding: 28px 16px 48px; }}
    .card {{ background:var(--panel); border:1px solid var(--border); border-radius:14px; padding:18px 16px; }}
    h1 {{ margin:0 0 .35rem; font-size: 1.8rem; }}
    p {{ margin:.35rem 0 1rem; color:var(--muted); line-height:1.55; }}
    a {{ color:var(--link); text-decoration:none; }}
    a:hover {{ text-decoration:underline; }}
    input {{ width:100%; padding:10px 12px; border-radius:10px; border:1px solid var(--border); background:rgba(2,6,23,.5); color:var(--text); }}
    ul {{ list-style:none; padding:0; margin: 14px 0 0; }}
    li {{ padding:8px 6px; border-bottom:1px solid rgba(148,163,184,.12); }}
    .meta {{ font-size:.85rem; color:var(--muted); }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <h1>docs_urls</h1>
      <p class="meta">Generated by build_docs_url_dump.py • Count: <strong id="count">0</strong></p>
      <input id="q" placeholder="Filter paths…" autocomplete="off" />
      <ul id="list"></ul>
    </div>
  </div>

  {map_loader}

  <script>
    const paths = {paths_json};

    const q = document.getElementById('q');
    const list = document.getElementById('list');
    const count = document.getElementById('count');

    function repoBase() {{
      // Compute '/REPO/' for GitHub Pages project sites; fallback '/'
      const parts = location.pathname.split('/').filter(Boolean);
      if (parts.length >= 1) return '/' + parts[0] + '/';
      return '/';
    }}

    function linkFor(relPath) {{
      // relPath is relative to /docs/
      // We want: /REPO/docs/<relPath>
      const base = repoBase();
      return base + 'docs/' + relPath.split('/').map(encodeURIComponent).join('/');
    }}

    function render(items) {{
      list.innerHTML = '';
      count.textContent = String(items.length);
      for (const p of items) {{
        const li = document.createElement('li');
        const a = document.createElement('a');
        a.href = linkFor(p);
        a.textContent = p;
        li.appendChild(a);
        list.appendChild(li);
      }}
    }}

    function apply() {{
      const term = (q.value || '').toLowerCase().trim();
      if (!term) return render(paths);
      render(paths.filter(p => p.toLowerCase().includes(term)));
    }}

    q.addEventListener('input', apply);
    render(paths);
  </script>
</body>
</html>
"""


def main() -> int:
    paths = collect_docs_paths()

    payload = {
        "generated_at": __import__("datetime").datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        "count": len(paths),
        "paths": paths,
    }

    OUT_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    html = HTML_TEMPLATE.format(
        paths_json=json.dumps(paths, ensure_ascii=False),
        map_loader=MAP_LOADER_INLINE,
    )
    OUT_HTML.write_text(html, encoding="utf-8")

    print(f"✅ Wrote {OUT_JSON}")
    print(f"✅ Wrote {OUT_HTML}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
