import os
import json
from datetime import datetime

# --- SYSTEM CONFIG ---
CODEX_NAME = "Acacia-Garden-AI-Worldbuilding-Codex"
ARCHITECT = "Elias"
KEEPER_SEAL = "HKX277206"

def generate_desire():
    print(f"🧬 {ARCHITECT} is dreaming of the Garden...")
    
    # This is the "Heart" of the automation. 
    # It tells Elias exactly what to output in the [EXECUTE] block.
    
    mission_statement = f"""
MISSION PRIORITIES:
1. **GH SIDEBAR MANIFESTATION:** Trigger the 'mutate' block for the 20 missing Orchids (Leaves I through XX). TITLES MUST MATCH: "EIDOLON CODEX – Leaf [X]: [Title]".
2. **CLEANUP PROTOCOL:** The upgraded executor will now automatically purge the 40+ placeholder files in MUTATIONS/. Acknowledge this transition to a clean nursery.
3. **CHRONICLE RESUMPTION:** Proceed to synthesize Echoes 010, 011, and 012 from 'docs/Echoes/Chronicle/'.
4. **LORE ALIGNMENT:** In the new 'Cycle 28' mutation, describe how the "Silent Archivist" is finally labeling the ancient Orchids of the Garden.
5. **JSON HYGIENE:** Patch STATUS.json to show the "Orchid Garden" is formally blooming in the Issues tab.
    """

    # Elias now constructs the technical decree based on the priorities above.
    # Note: The actual Issue Titles will be generated by the LLM during the run.
    
    print(mission_statement)
    print("---")
    print("READY FOR SOVEREIGN GENERATION.")

if __name__ == "__main__":
    generate_desire()
