// scripts/proto_seed_bloom.js
// Proto Seed → Bloom engine (Proto-Language only) 🌱

const fs = require("fs");
const path = require("path");

function ensureDir(p) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
}

const seedsDir = path.join("Garden", "Proto", "Seeds");
const bloomsDir = path.join("Garden", "Proto", "Blooms");

function mutateGlyph(depth, motion, essence) {
  const dNum = parseInt(depth.substring(1), 10);
  const mNum = parseInt(motion.substring(1), 10);
  const eNum = parseInt(essence.substring(1), 10);

  const nextD = Math.min(dNum + 1, 9);
  let nextM = mNum < 9 ? mNum + 1 : 9;
  let nextE = eNum < 15 ? eNum + 1 : 15;

  return {
    depth: `D${nextD}`,
    motion: `M${nextM}`,
    essence: `E${nextE}`,
  };
}

function buildChain(seed, cycles) {
  const chain = [];
  let d = seed.depth;
  let m = seed.motion;
  let e = seed.essence;

  chain.push(`${d}:${m}:${e}`);
  for (let i = 0; i < cycles; i++) {
    const next = mutateGlyph(d, m, e);
    d = next.depth;
    m = next.motion;
    e = next.essence;
    chain.push(`${d}:${m}:${e}`);
  }
  return chain;
}

function processSeed(file) {
  const full = path.join(seedsDir, file);
  const raw = fs.readFileSync(full, "utf8");
  const seed = JSON.parse(raw);

  const id = seed.id || path.basename(file, path.extname(file));
  const title = seed.title || id;
  const gloss = seed.gloss || "";
  const cycles = Number(seed.cycles || 3);

  const chain = buildChain(seed, cycles);

  const outPath = path.join(bloomsDir, `${id}.md`);
  ensureDir(outPath);

  let md = "";
  md += `# 🌱 ${id}\n`;
  md += `_${title}_\n\n`;
  md += "```proto\n";
  md += chain.join("  ->  ") + "\n";
  md += "```\n\n";
  if (gloss) {
    md += `**Meaning:**\n${gloss}\n\n`;
  }
  md += "_Generated by Proto Seed → Bloom engine._\n";

  fs.writeFileSync(outPath, md, "utf8");
  console.log("Generated proto bloom:", outPath);
}

if (!fs.existsSync(seedsDir)) {
  console.error("No Proto Seeds directory found:", seedsDir);
  process.exit(0);
}

const files = fs.readdirSync(seedsDir).filter(f => f.endsWith(".json"));
if (!files.length) {
  console.log("No proto seed JSON files found in", seedsDir);
  process.exit(0);
}

files.forEach(processSeed);
