name: grow-and-archive

on:
  workflow_dispatch:

jobs:
  grow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        pip install openai==1.10.0

    # ---------------------------------------------------------
    # 1. Grow a new Echo (garden_lore_helper.py)
    # ---------------------------------------------------------
    - name: Grow Lore (Echo)
      run: |
        echo "[AeonHeartbeat] Growing new Echo..."
        python tools/garden_lore_helper.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    # ---------------------------------------------------------
    # 2. Grow a new helper script (garden_code_helper.py)
    # ---------------------------------------------------------
    - name: Grow Code (Helper script)
      run: |
        echo "[AeonHeartbeat] Growing new Garden helper script..."
        python tools/garden_code_helper.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    # ---------------------------------------------------------
    # 3. Run Archivist (optional — generates dashboard later)
    # ---------------------------------------------------------
    - name: Run Aquila / Aeon Archivist
      run: |
        echo "[Archivist] Archiving and updating dashboard..."
        # Placeholder for future dashboard update tool
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    # ---------------------------------------------------------
    # 4. Commit changes automatically
    # ---------------------------------------------------------
    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "AeonBot"
        git add .
        git commit -m "Aeon Growth: $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

    # ---------------------------------------------------------
    # 5. Push changes back to main
    # ---------------------------------------------------------
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
