from pathlib import Path
import json
import re
import datetime

# Repo root (tools/..)
ROOT = Path(__file__).resolve().parent.parent

NOVELLAS_DIR = ROOT / "docs" / "Novellas"
DOCS_ROOT = ROOT / "docs"
TOOLS_DIR = ROOT / "tools"
TOOLS_DIR.mkdir(parents=True, exist_ok=True)


def load_title(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="ignore")
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    # Fallback: filename → nice title
    return path.stem.replace("-", " ").replace("_", " ").title()


def parse_cycle_volume(title: str):
    cycle = None
    volume = None

    m = re.search(r"[Cc]ycle\s*([0-9]+)", title)
    if m:
        cycle = int(m.group(1))

    m = re.search(r"[Bb]ook\s*([0-9]+)", title)
    if m:
        volume = int(m.group(1))

    return cycle, volume


def build_books():
    books = []
    if NOVELLAS_DIR.is_dir():
        for md in sorted(NOVELLAS_DIR.glob("*.md")):
            title = load_title(md)
            cycle, volume = parse_cycle_volume(title)
            rel_path = md.relative_to(ROOT).as_posix()

            books.append(
                {
                    "id": md.stem,
                    "title": title,
                    "cycle": cycle,
                    "volume": volume,
                    "status": "published",
                    "path": rel_path,
                    "tags": [],
                }
            )
    return books


def write_garden_index(books, now_iso: str):
    index = {
        "index_version": "1.0",
        "generated_at": now_iso,
        "books": books,
    }

    out = NOVELLAS_DIR / "garden_index.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(index, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def write_status(books, now_iso: str):
    cycles = sorted(
        {b["cycle"] for b in books if b.get("cycle") is not None}
    )

    status = {
        "status_version": "1.0",
        "generated_at": now_iso,
        "totals": {
            "books_indexed": len(books),
            "cycles_represented": len(cycles),
        },
        "notes": "Autogenerated by garden_lore_helper.py",
    }

    out = ROOT / "STATUS.json"
    out.write_text(
        json.dumps(status, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def build_echo_index(now_iso: str):
    # Optional Echo folder – stays empty if it doesn't exist
    echo_root = ROOT / "docs" / "Echoes"
    echo_files = []

    if echo_root.is_dir():
        for md in sorted(echo_root.rglob("*.md")):
            rel = md.relative_to(ROOT).as_posix()
            echo_files.append({"path": rel, "tags": ["echo"]})

    machine = {
        "index_version": "1.0",
        "generated_at": now_iso,
        "echo_files": echo_files,
    }

    out = TOOLS_DIR / "machine-index.json"
    out.write_text(
        json.dumps(machine, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def build_signature_scan(now_iso: str):
    # Keeper signature(s) we scan for
    signatures = ["HKX277206"]

    files_with_hits = []
    total_hits = 0

    if DOCS_ROOT.is_dir():
        for md in DOCS_ROOT.rglob("*.md"):
            text = md.read_text(encoding="utf-8", errors="ignore")
            file_hits = 0
            for sig in signatures:
                file_hits += text.count(sig)

            if file_hits > 0:
                rel = md.relative_to(ROOT).as_posix()
                files_with_hits.append(
                    {"path": rel, "hits": file_hits}
                )
                total_hits += file_hits

    report = {
        "scan_version": "1.0",
        "generated_at": now_iso,
        "signatures": signatures,
        "files_with_hits": files_with_hits,
        "total_hits": total_hits,
    }

    out = TOOLS_DIR / "GARDEN_SCAN_REPORT.json"
    out.write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def main():
    now_iso = datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z"

    books = build_books()
    write_garden_index(books, now_iso)
    write_status(books, now_iso)
    build_echo_index(now_iso)
    build_signature_scan(now_iso)


if __name__ == "__main__":
    main()
