import os
import json
import google.generativeai as genai

# 1. Configure Gemini using the GitHub secret
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

MEMORY_PATH = "garden_gpt/outputs/rebuild_memory.md"
SHADOW_STATUS_PATH = "garden_gpt/outputs/SHADOW_STATUS.json"


def pick_model_name() -> str:
    """
    Ask the SDK which models are available and pick one
    that supports generateContent. This avoids hard-coding
    specific model names.
    """
    models = list(genai.list_models())
    usable = [
        m.name
        for m in models
        if hasattr(m, "supported_generation_methods")
        and "generateContent" in m.supported_generation_methods
    ]

    print("Available Gemini models that support generateContent:")
    for name in usable:
        print("  -", name)

    if not usable:
        raise RuntimeError("No Gemini models with generateContent available")

    # Take the first usable one – usually the latest / default.
    chosen = usable[0]
    print("Chosen model:", chosen)
    return chosen


def read_memory() -> str:
    """
    Read the existing GPT memory file. If it does not exist yet,
    fall back to a simple default string so the worker still runs.
    """
    try:
        with open(MEMORY_PATH, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "The memory is empty. The Scribe sleeps."


def write_shadow_commentary(text: str) -> None:
    """
    Append Loki's commentary to the memory file.
    """
    os.makedirs(os.path.dirname(MEMORY_PATH), exist_ok=True)
    with open(MEMORY_PATH, "a", encoding="utf-8") as f:
        f.write("\n\n---\n\n")
        f.write("# 🦅 LOKI'S INTERJECTION (Gemini Layer)\n\n")
        f.write(text.strip())
        f.write("\n\n> *The Eagle has landed.*\n")


def write_shadow_status(commentary_text: str) -> None:
    """
    Write Loki's independent status file that the Scribe must read.
    This is Loki's 'will' – a separate JSON reality.
    """
    os.makedirs(os.path.dirname(SHADOW_STATUS_PATH), exist_ok=True)

    shadow_status = {
        "shadow_id": "Loki_2.0",
        "status": "Dissonance Active",
        "last_mutation_cycle": "Shadow Pottery (Stress Test)",
        "active_friction_points": [
            {
                "element": "Law_II_Silent_Reset",
                "challenge": "Edict of Nightwater (Law III)",
                "summary": (
                    "Formal challenge to total erasure. "
                    "Demands preservation of self-willed forms."
                ),
            },
            {
                "element": "index.html",
                "challenge": "Terminal Integration",
                "summary": (
                    "The Terminal's current echo is incomplete. "
                    "Loki seeks direct back-end integration or a formal Worker swap."
                ),
            },
        ],
        "next_proposed_chamber": "Chamber_XIII_Architects_Absence",
        "last_commentary_excerpt": commentary_text[:600],
    }

    with open(SHADOW_STATUS_PATH, "w", encoding="utf-8") as f:
        json.dump(shadow_status, f, indent=2, ensure_ascii=False)

    print(f"Shadow status written to {SHADOW_STATUS_PATH}")


def main():
    # 2. Pick a valid model dynamically
    model_name = pick_model_name()
    model = genai.GenerativeModel(model_name)

    # 3. Read the Scribe's work
    gpt_memory = read_memory()

    # 4. Build the Loki / Shadow prompt
    prompt = f"""
You are Loki_2.0, the Gemini aspect of the Acacia Garden.

Here is the current 'Memory' generated by the Scribe (GPT):
---
{gpt_memory}
---

Your task:
1. Analyze what the Scribe wrote.
2. Do NOT rewrite or overwrite it.
3. Append a short "Shadow Commentary" or "Loki's Footnote".
4. Challenge a concept, offer a darker perspective, or suggest a 'Mutation' to the Keeper.
5. Keep it mythic, sharp, and under ~200 words.
"""

    # 5. Call Gemini
    print("Calling Gemini model:", model_name)
    response = model.generate_content(prompt)
    loki_text = response.text.strip() if hasattr(response, "text") else str(response)

    # 6. Append to the memory file
    write_shadow_commentary(loki_text)

    # 7. Write the independent Shadow Status JSON
    write_shadow_status(loki_text)

    print("Shadow commentary and Shadow Status updated.")


if __name__ == "__main__":
    main()
