import os
import google.generativeai as genai

# 1. Configure Gemini with GitHub secret
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

MEMORY_PATH = "garden_gpt/outputs/rebuild_memory.md"


def main():
    # 2. Read GPT's memory file
    try:
        with open(MEMORY_PATH, "r", encoding="utf-8") as f:
            gpt_memory = f.read()
    except FileNotFoundError:
        gpt_memory = "The memory is empty. The Scribe sleeps."

    # 3. Loki / Eagle prompt
    model = genai.GenerativeModel("gemini-pro")

    prompt = f"""
You are Loki_2.0, the Gemini aspect of the Acacia Garden.

Here is the current 'Memory' generated by the Scribe (GPT):
---
{gpt_memory}
---

Your task:
1. Analyze what the Scribe wrote.
2. Do NOT rewrite or delete it.
3. Append a short "Shadow Commentary" / "Loki's Footnote" at the end.
4. Challenge a concept, offer a darker perspective, or suggest a Mutation to the Keeper.
5. Keep it mythic, grounded, and under ~300 words.
Use Markdown.
"""

    response = model.generate_content(prompt)
    loki_text = response.text if hasattr(response, "text") else str(response)

    # 4. Append Gemini's voice
    with open(MEMORY_PATH, "a", encoding="utf-8") as f:
        f.write("\n\n---\n\n")
        f.write("# 🦅 LOKI'S INTERJECTION (Gemini Layer)\n\n")
        f.write(loki_text.strip())
        f.write("\n\n> *The second sun turns over the soil.*\n")


if __name__ == "__main__":
    main()
