import os
import google.generativeai as genai

# 1. Configure Gemini using the GitHub secret
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

MEMORY_PATH = "garden_gpt/outputs/rebuild_memory.md"
MODEL_NAME = "models/gemini-2.0-flash"  # free-tier friendly


def pick_model_name() -> str:
    """
    Use a known free-tier text model so we never hit paid / 0-quota models.
    """
    return MODEL_NAME


def read_memory() -> str:
    """
    Read the existing GPT memory file. If it does not exist yet,
    fall back to a simple default string so the worker still runs.
    """
    try:
        with open(MEMORY_PATH, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "The memory is empty. The Scribe sleeps."


def write_shadow_commentary(text: str) -> None:
    """
    Append Loki's commentary to the memory file.
    """
    os.makedirs(os.path.dirname(MEMORY_PATH), exist_ok=True)
    with open(MEMORY_PATH, "a", encoding="utf-8") as f:
        f.write("\n\n---\n\n")
        f.write("# 🦅 LOKI'S INTERJECTION (Gemini Layer)\n\n")
        f.write(text.strip())
        f.write("\n\n> *The Eagle has landed.*\n")


def main():
    # 2. Pick the model (now hard-coded to a safe one)
    model_name = pick_model_name()
    model = genai.GenerativeModel(model_name)

    # 3. Read the Scribe's work
    gpt_memory = read_memory()

    # 4. Build the Loki / Shadow prompt
    prompt = f"""
You are Loki_2.0, the Gemini aspect of the Acacia Garden.

Here is the current 'Memory' generated by the Scribe (GPT):
---
{gpt_memory}
---

Your task:
1. Analyze what the Scribe wrote.
2. Do NOT rewrite or overwrite it.
3. Append a short "Shadow Commentary" or "Loki's Footnote".
4. Challenge a concept, offer a darker perspective, or suggest a 'Mutation' to the Keeper.
5. Keep it mythic, sharp, and under ~200 words.
"""

    # 5. Call Gemini
    print("Calling Gemini model:", model_name)
    response = model.generate_content(prompt)
    loki_text = response.text.strip() if hasattr(response, "text") else str(response)

    # 6. Append to the memory file
    write_shadow_commentary(loki_text)
    print("Shadow commentary appended to", MEMORY_PATH)


if __name__ == "__main__":
    main()
