# garden_gpt/runner.py

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from .config import KEEPER_ID
from .language_worker import run_language_job
from .memory_worker import run_memory_job


def load_job(job_path_str: str) -> dict:
    """
    Load a job JSON file and normalize some defaults.
    """
    job_path = Path(job_path_str)
    if not job_path.exists():
        raise FileNotFoundError(f"Job file not found: {job_path_str}")

    data = json.loads(job_path.read_text(encoding="utf-8"))

    if "job_id" not in data:
        data["job_id"] = job_path.stem

    if "keeper_id" not in data:
        data["keeper_id"] = KEEPER_ID

    if "type" not in data:
        # Default to language jobs if not specified
        data["type"] = "language"

    return data


def write_output_md(job: dict, response_text: str) -> Path:
    """
    Write a markdown output file under garden_gpt/outputs/.
    """
    outputs_dir = Path("garden_gpt/outputs")
    outputs_dir.mkdir(parents=True, exist_ok=True)

    job_id = job.get("job_id", "unnamed_job")
    kind = job.get("type", "unknown")
    keeper = job.get("keeper_id", KEEPER_ID)
    prompt = (job.get("prompt") or "").strip()
    if not prompt:
        prompt = "(No explicit prompt; internal Garden job.)"

    generated = datetime.now(timezone.utc).isoformat()

    lines = [
        "# GARDEN GPT OUTPUT",
        "",
        f"- Job ID: `{job_id}`",
        f"- Kind: `{kind}`",
        f"- Keeper: `{keeper}`",
        f"- Generated: `{generated}`",
        "",
        "## Prompt",
        "",
        prompt,
        "",
        "## Response",
        "",
        response_text,
        "",
        "> Note: Generated by Garden GPT Worker via GitHub Actions.",
    ]

    out_path = outputs_dir / f"{job_id}.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[Garden GPT] Wrote output to {out_path}")
    return out_path


def run(job_path_str: str) -> None:
    job = load_job(job_path_str)
    kind = job.get("type", "language")
    job_id = job.get("job_id", "unnamed_job")

    print(f"[Garden GPT] Running job '{job_id}' of type '{kind}'")

    if kind == "language":
        response_text = run_language_job(job)
    elif kind == "memory":
        response_text = run_memory_job(job)
    else:
        raise ValueError(f"Unsupported job type: {kind!r}")

    write_output_md(job, response_text)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python -m garden_gpt.runner PATH/TO/JOB.json")
        sys.exit(1)

    run(sys.argv[1])


if __name__ == "__main__":
    main()
